# ==============================================================================
# Merged Lakeflow Source: sqs_microflex
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import Any, Iterator
import json
import time

from botocore.exceptions import ClientError
from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import boto3


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/sources/sqs_microflex/sqs_microflex_schemas.py
    ########################################################

    QUEUES_SCHEMA = StructType(
        [
            StructField("queue_url", StringType(), nullable=False),
            StructField("queue_name", StringType(), nullable=True),
            StructField("queue_arn", StringType(), nullable=True),
            StructField("approximate_number_of_messages", LongType(), nullable=True),
            StructField("approximate_number_of_messages_not_visible", LongType(), nullable=True),
            StructField("approximate_number_of_messages_delayed", LongType(), nullable=True),
            StructField("created_timestamp", TimestampType(), nullable=True),
            StructField("last_modified_timestamp", TimestampType(), nullable=True),
            StructField("visibility_timeout", LongType(), nullable=True),
            StructField("maximum_message_size", LongType(), nullable=True),
            StructField("message_retention_period", LongType(), nullable=True),
            StructField("delay_seconds", LongType(), nullable=True),
            StructField("receive_message_wait_time_seconds", LongType(), nullable=True),
            StructField("policy", StringType(), nullable=True),
            StructField("redrive_policy", StringType(), nullable=True),
            StructField("redrive_allow_policy", StringType(), nullable=True),
            StructField("fifo_queue", BooleanType(), nullable=True),
            StructField("content_based_deduplication", BooleanType(), nullable=True),
            StructField("deduplication_scope", StringType(), nullable=True),
            StructField("fifo_throughput_limit", StringType(), nullable=True),
            StructField("kms_master_key_id", StringType(), nullable=True),
            StructField("kms_data_key_reuse_period_seconds", LongType(), nullable=True),
            StructField("sqs_managed_sse_enabled", BooleanType(), nullable=True),
        ]
    )

    QUEUES_METADATA = {
        "primary_keys": ["queue_url"],
        "cursor_field": "",
        "ingestion_type": "snapshot",
    }

    # ---------------------------------------------------------------------------
    # Messages table schema
    # ---------------------------------------------------------------------------
    MESSAGES_SCHEMA = StructType(
        [
            StructField("message_id", StringType(), nullable=False),
            StructField("queue_url", StringType(), nullable=True),
            StructField("receipt_handle", StringType(), nullable=True),
            StructField("body", StringType(), nullable=True),
            StructField("md5_of_body", StringType(), nullable=True),
            StructField("md5_of_message_attributes", StringType(), nullable=True),
            StructField("sender_id", StringType(), nullable=True),
            StructField("sent_timestamp", TimestampType(), nullable=True),
            StructField("approximate_receive_count", LongType(), nullable=True),
            StructField("approximate_first_receive_timestamp", TimestampType(), nullable=True),
            StructField("sequence_number", StringType(), nullable=True),
            StructField("message_deduplication_id", StringType(), nullable=True),
            StructField("message_group_id", StringType(), nullable=True),
            StructField("aws_trace_header", StringType(), nullable=True),
            StructField("dead_letter_queue_source_arn", StringType(), nullable=True),
            StructField("message_attributes", StringType(), nullable=True),
        ]
    )

    MESSAGES_METADATA = {
        "primary_keys": ["message_id"],
        "cursor_field": "sent_timestamp",
        "ingestion_type": "append",
    }

    # ---------------------------------------------------------------------------
    # Retry constants
    # ---------------------------------------------------------------------------
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # ---------------------------------------------------------------------------
    # AWS attribute-name-to-field-name mapping for queues
    # ---------------------------------------------------------------------------
    QUEUE_ATTR_MAP = {
        "QueueArn": "queue_arn",
        "ApproximateNumberOfMessages": "approximate_number_of_messages",
        "ApproximateNumberOfMessagesNotVisible": "approximate_number_of_messages_not_visible",
        "ApproximateNumberOfMessagesDelayed": "approximate_number_of_messages_delayed",
        "CreatedTimestamp": "created_timestamp",
        "LastModifiedTimestamp": "last_modified_timestamp",
        "VisibilityTimeout": "visibility_timeout",
        "MaximumMessageSize": "maximum_message_size",
        "MessageRetentionPeriod": "message_retention_period",
        "DelaySeconds": "delay_seconds",
        "ReceiveMessageWaitTimeSeconds": "receive_message_wait_time_seconds",
        "Policy": "policy",
        "RedrivePolicy": "redrive_policy",
        "RedriveAllowPolicy": "redrive_allow_policy",
        "FifoQueue": "fifo_queue",
        "ContentBasedDeduplication": "content_based_deduplication",
        "DeduplicationScope": "deduplication_scope",
        "FifoThroughputLimit": "fifo_throughput_limit",
        "KmsMasterKeyId": "kms_master_key_id",
        "KmsDataKeyReusePeriodSeconds": "kms_data_key_reuse_period_seconds",
        "SqsManagedSseEnabled": "sqs_managed_sse_enabled",
    }

    # Fields that should be parsed as integers
    QUEUE_INT_FIELDS = {
        "approximate_number_of_messages",
        "approximate_number_of_messages_not_visible",
        "approximate_number_of_messages_delayed",
        "created_timestamp",
        "last_modified_timestamp",
        "visibility_timeout",
        "maximum_message_size",
        "message_retention_period",
        "delay_seconds",
        "receive_message_wait_time_seconds",
        "kms_data_key_reuse_period_seconds",
    }

    # Fields that should be parsed as booleans (from string "true"/"false")
    QUEUE_BOOL_FIELDS = {
        "fifo_queue",
        "content_based_deduplication",
        "sqs_managed_sse_enabled",
    }


    def parse_queue_attributes(queue_url: str, attrs: dict) -> dict:
        """Convert raw AWS GetQueueAttributes response into a connector record dict."""
        queue_name = queue_url.rstrip("/").split("/")[-1]
        record = {
            "queue_url": queue_url,
            "queue_name": queue_name,
        }

        for aws_name, field_name in QUEUE_ATTR_MAP.items():
            raw = attrs.get(aws_name)
            if raw is None:
                record[field_name] = None
                continue

            if field_name in QUEUE_BOOL_FIELDS:
                record[field_name] = raw.lower() == "true"
            elif field_name in QUEUE_INT_FIELDS:
                record[field_name] = int(raw)
            else:
                record[field_name] = raw

        return record


    def parse_message(msg: dict, queue_url: str) -> dict:
        """Convert a raw SQS ReceiveMessage response message into a connector record dict."""
        sys_attrs = msg.get("Attributes", {})
        user_attrs = msg.get("MessageAttributes", {})

        # Serialize user message attributes to a JSON string for storage.
        # Each attribute has StringValue/BinaryValue/DataType — we keep only
        # the string-representable parts.
        serialized_attrs = None
        if user_attrs:
            simplified = {}
            for k, v in user_attrs.items():
                simplified[k] = {
                    "DataType": v.get("DataType", ""),
                    "StringValue": v.get("StringValue"),
                }
            serialized_attrs = json.dumps(simplified)

        sent_ts_raw = sys_attrs.get("SentTimestamp")
        sent_ts = int(sent_ts_raw) / 1000.0 if sent_ts_raw else None

        first_recv_raw = sys_attrs.get("ApproximateFirstReceiveTimestamp")
        first_recv_ts = int(first_recv_raw) / 1000.0 if first_recv_raw else None

        recv_count_raw = sys_attrs.get("ApproximateReceiveCount")
        recv_count = int(recv_count_raw) if recv_count_raw else None

        return {
            "message_id": msg["MessageId"],
            "queue_url": queue_url,
            "receipt_handle": msg.get("ReceiptHandle"),
            "body": msg.get("Body"),
            "md5_of_body": msg.get("MD5OfBody"),
            "md5_of_message_attributes": msg.get("MD5OfMessageAttributes"),
            "sender_id": sys_attrs.get("SenderId"),
            "sent_timestamp": sent_ts,
            "approximate_receive_count": recv_count,
            "approximate_first_receive_timestamp": first_recv_ts,
            "sequence_number": sys_attrs.get("SequenceNumber"),
            "message_deduplication_id": sys_attrs.get("MessageDeduplicationId"),
            "message_group_id": sys_attrs.get("MessageGroupId"),
            "aws_trace_header": sys_attrs.get("AWSTraceHeader"),
            "dead_letter_queue_source_arn": sys_attrs.get("DeadLetterQueueSourceArn"),
            "message_attributes": serialized_attrs,
        }


    ########################################################
    # src/databricks/labs/community_connector/sources/sqs_microflex/sqs_microflex.py
    ########################################################

    RETRIABLE_ERROR_CODES = {"RequestThrottled", "OverLimit", "InternalError", "ServiceUnavailable"}

    SUPPORTED_TABLES = ["queues", "messages"]


    class SqsMicroflexLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for AWS SQS."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._client = None

        @property
        def client(self):
            """Lazily create the boto3 SQS client to avoid pickling thread locks."""
            if self._client is None:
                client_kwargs = {
                    "service_name": "sqs",
                    "region_name": self.options["aws_region"],
                    "aws_access_key_id": self.options["aws_access_key_id"],
                    "aws_secret_access_key": self.options["aws_secret_access_key"],
                }
                session_token = self.options.get("aws_session_token")
                if session_token:
                    client_kwargs["aws_session_token"] = session_token
                self._client = boto3.client(**client_kwargs)
            return self._client

        # ------------------------------------------------------------------
        # Interface methods
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            if table_name == "queues":
                return QUEUES_SCHEMA
            return MESSAGES_SCHEMA

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            if table_name == "queues":
                return dict(QUEUES_METADATA)
            return dict(MESSAGES_METADATA)

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            if table_name == "queues":
                return self._read_queues(table_options)
            return self._read_messages(start_offset, table_options)

        # ------------------------------------------------------------------
        # Internal helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {SUPPORTED_TABLES}"
                )

        def _call_with_retry(self, api_method, **kwargs):
            """Call a boto3 SQS API method with exponential backoff on retriable errors."""
            backoff = INITIAL_BACKOFF
            for attempt in range(MAX_RETRIES):
                try:
                    return api_method(**kwargs)
                except ClientError as exc:
                    code = exc.response["Error"]["Code"]
                    if code not in RETRIABLE_ERROR_CODES:
                        raise
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(backoff)
                        backoff *= 2
                    else:
                        raise

        # ------------------------------------------------------------------
        # Queues table (snapshot)
        # ------------------------------------------------------------------

        def _list_all_queue_urls(self) -> list[str]:
            """Paginate through ListQueues to discover all queue URLs."""
            queue_urls = []
            params = {"MaxResults": 100}

            while True:
                resp = self._call_with_retry(self.client.list_queues, **params)
                queue_urls.extend(resp.get("QueueUrls", []))
                next_token = resp.get("NextToken")
                if not next_token:
                    break
                params["NextToken"] = next_token

            return queue_urls

        def _read_queues(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Full-refresh read of all queues and their attributes."""
            queue_urls = self._list_all_queue_urls()

            records = []
            for queue_url in queue_urls:
                resp = self._call_with_retry(
                    self.client.get_queue_attributes,
                    QueueUrl=queue_url,
                    AttributeNames=["All"],
                )
                attrs = resp.get("Attributes", {})
                records.append(parse_queue_attributes(queue_url, attrs))

            return iter(records), {}

        # ------------------------------------------------------------------
        # Messages table (append)
        # ------------------------------------------------------------------

        # Maximum messages to read per micro-batch to avoid unbounded polling.
        MAX_BATCH_SIZE = 1000

        def _read_messages(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read messages from all queues in bounded batches.

            Polling strategy:
            - Discover all queues via ListQueues.
            - For each queue, call ReceiveMessage repeatedly (max 10 per call)
              until MAX_BATCH_SIZE is reached or the queue returns no messages.
            - Messages are deleted after being read so they are not returned
              again on subsequent polls.
            - The offset tracks the max sent_timestamp seen so the framework
              can detect progress between batches.
            """
            max_batch = int(table_options.get("max_records_per_batch", str(self.MAX_BATCH_SIZE)))
            last_ts = start_offset.get("last_sent_timestamp", "0") if start_offset else "0"

            queue_urls = self._list_all_queue_urls()

            records = []
            max_ts = last_ts
            for queue_url in queue_urls:
                if len(records) >= max_batch:
                    break
                self._poll_queue(queue_url, records, max_batch - len(records))
                # Track the max sent_timestamp across all records
                for rec in records:
                    ts = rec.get("sent_timestamp")
                    if ts is not None:
                        ts_str = str(ts)
                        if ts_str > max_ts:
                            max_ts = ts_str

            if not records:
                return iter([]), start_offset or {}

            end_offset = {"last_sent_timestamp": max_ts}
            return iter(records), end_offset

        def _poll_queue(
            self, queue_url: str, records: list[dict], remaining: int
        ) -> None:
            """Receive messages from a single queue up to the remaining limit.

            Messages are deleted from SQS after being read so they are not
            returned again on subsequent polls.  A longer VisibilityTimeout
            (300 s) is used to prevent other consumers from seeing the same
            messages while this batch is being processed.
            """
            while remaining > 0:
                fetch_size = min(10, remaining)
                resp = self._call_with_retry(
                    self.client.receive_message,
                    QueueUrl=queue_url,
                    MaxNumberOfMessages=fetch_size,
                    MessageSystemAttributeNames=["All"],
                    MessageAttributeNames=["All"],
                    WaitTimeSeconds=1,
                    VisibilityTimeout=300,
                )
                messages = resp.get("Messages", [])
                if not messages:
                    break

                delete_entries = []
                for msg in messages:
                    records.append(parse_message(msg, queue_url))
                    delete_entries.append(
                        {"Id": msg["MessageId"], "ReceiptHandle": msg["ReceiptHandle"]}
                    )
                    remaining -= 1

                # Delete the batch from SQS so they are not re-read.
                self._call_with_retry(
                    self.client.delete_message_batch,
                    QueueUrl=queue_url,
                    Entries=delete_entries,
                )


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = SqsMicroflexLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
